plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  
relative_links:
  enabled: true
  collections: true
url: "https://pod.gonzalohirsch.com"
baseurl: "/" 
title: Resumen de POD
include:
  - /resumen/resumen.md
  - /resumen/parte-1.md
  - /resumen/parte-2.md
  - /resumen/parte-3.md
  - /resumen/parte-4.md
  - /resumen/parte-5.md
  - /resumen/parte-6.md
  - /resumen/parte-7.md
  - /index.md
theme: jekyll-theme-minimal

twitter:
  'twitter:username': '@GonzaloHirsch'
  username: '@GonzaloHirsch'
  site: '@GonzaloHirsch'
  card: summary

google_analytics: G-RH9ZR9M5FC
